enyo.depends(
    "AutoCompleteInputDecorator.js",
	"Accordion.js",
    "Delegator.js",
    "Menu.js",
    "MenuItem.js",
    "TagInput.js",
    "PrefixedTagInput.js",
    "TypeAheadInput.js",
    "ComboInput.js",
    "WheelPicker.js",
    "WheelPickerClient.js",
    "Overlay.js",
    "IntegerWheelPicker.js",
    "ColorProgressBar.js"
);